"""Drop Ledger table

Revision ID: f3b6d1fc7cae
Revises: 1221a679d242
Create Date: 2026-05-02 15:52:21.279977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b6d1fc7cae'
down_revision: Union[str, Sequence[str], None] = '1221a679d242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_block_number'))

    op.drop_table('ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('block_number', sa.INTEGER(), nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('previous_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('drug_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('block_number'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_block_number'), ['block_number'], unique=False)

    # ### end Alembic commands ###
